### ISSUE TITLE
Error during compiling

### ISSUE THREAD

**Issue by rkinas** [ivashmak/vsac#5]
I am trying to compile VSAC but ... got error:

/working/vsac/src/utils.cpp:961:55: error: no match for ‘operator/’ (operand types are ‘cv::Matx33d’ {aka ‘cv::Matx<double, 3, 3>’} and ‘double’)
  961 |         const double s1_sqr = pow(1/cv::determinant(A / A(2,2)), 2);
      |                                                     ~ ^ ~~~~~~
      |                                                     |    |
      |                                                     |    double
      |                                                     cv::Matx33d {aka cv::Matx<double, 3, 3>}

any idea how to fix it?

**Comment by ivashmak** [comment]
What OpenCV version are you using?

**Comment by rkinas** [comment]
!sudo apt -y install libopencv-dev python3-opencv

is looks for me that 4.2:

libopencv-contrib-dev libopencv-contrib4.2 libopencv-core-dev
  libopencv-core4.2 libopencv-dnn-dev libopencv-dnn4.2
  libopencv-features2d-dev libopencv-features2d4.2 libopencv-flann-dev
  libopencv-flann4.2 libopencv-highgui-dev libopencv-highgui4.2
  libopencv-imgcodecs-dev libopencv-imgcodecs4.2 libopencv-imgproc-dev
  libopencv-imgproc4.2 libopencv-ml-dev libopencv-ml4.2
  libopencv-objdetect-dev libopencv-objdetect4.2 libopencv-photo-dev
  libopencv-photo4.2 libopencv-shape-dev libopencv-shape4.2
  libopencv-stitching-dev libopencv-stitching4.2 libopencv-superres-dev
  libopencv-superres4.2 libopencv-ts-dev libopencv-video-dev
  libopencv-video4.2 libopencv-videoio-dev libopencv-videoio4.2
  libopencv-videostab-dev libopencv-videostab4.2 libopencv-viz-dev
  libopencv-viz4.2 libopencv4.2-java libopencv4.2-jni libopenexr-dev

**Comment by ivashmak** [comment]
OpenCV version seems alright. I have never had this error before, so I do not know exactly how to fix it.
The problem appears to be in "A / A(2,2)" division of matrix Matx by double. Maybe try to replace it by "A * (1/A(2,2))"

**Comment by rkinas** [comment]
Thank you for solution - utils.cpp now compiled.

I almost finished .... but next error appeared ...

/working/vsac/lib/pybind11/include/pybind11/detail/common.h:167:10: fatal error: Python.h: No such file or directory
  167 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pvsac.dir/build.make:63: CMakeFiles/pvsac.dir/python/bindings.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:130: CMakeFiles/pvsac.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 87%] Building CXX object CMakeFiles/samples.dir/samples/samples.cpp.o
/working/vsac/samples/detector.cpp:2:10: fatal error: opencv2/xfeatures2d.hpp: No such file or directory
    2 | #include <opencv2/xfeatures2d.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by rkinas** [comment]
1. I changed code and compiled without problem. I had to install and upgrade many packages  ... and change setup.py to make it works (soon provide you my notebook).
2. I have another problem with importing package. It is probably easy to fix but ... not success so far.

a. installed package by python ./setup.py install  (made distribution as well to install by pip command). Then I created new notebook and tried to import pvsac

import pvsac 

does not work -> ModuleNotFoundError: No module named 'pvsac'

but ... when I run like in your manual  python ./python/test.py

it works .... :)

**Comment by HJoonKwon** [comment]
@rkinas Did you compile the module in your local env or manage to do it in the online notebook?

**Comment by rkinas** [comment]
Online notebook (Kaggle). It works but had to install/upgrade many packages to run it. I will provide notebook in 6-7 days after Image Matching Challange 2022 finish. VSAC is ... very vary very fast compared to CV2.MAGSAC/RANSAC.

**Comment by rkinas** [comment]
Notebook to installation on Kaggle you can find here: https://www.kaggle.com/code/remekkinas/vsac-on-kaggle
