### ISSUE TITLE
p3p result turns out discrepancy with GT

### ISSUE THREAD

**Issue by wanyunfeiAlex** [ivashmak/vsac#6]
hi, I run vsac to solve p3p problem using "pnp_scene_from_tless.txt" in the project. The result seems not right:

what I get :
Number of inliers 222 / 688; Number of iterations 61 / 2000; Time (ms) 19.509
Found model:
[-209.1158173824971, 1084.155348585346, -268.1585201209719, 292641.3313655289;
 505.1749234728141, -50.32278388992128, -988.8092772521812, 157376.9448546263;
 -0.7415449823152296, 0.02883156902290912, -0.6702833578650025, 831.4390294138603]

ground truth in txt:
0.07256981223341355 0.9972455325179528 0.01532873854535105 -11.299200057983398
0.6744825303876085 -0.03774878426213166 -0.7373251287516652 -74.21690368652344
**_-0.7347155494164634_** 0.06384651251020423 **_-0.6753641123763895 834.5928344726562_**

noted that in the last row , col0, col2, col3,  calculated matrix seems consist with the GT, but other elements in this matrix are not.

my steps:
1.unzip the code
2.comment other sample code in main.cpp, only use Samples::ESTIMATION_TASK::PROJECTION_MAT_P3P
3.build and run ./vsac

maybe my third-party library versions are not right? I'm running out of clues. Please help me, thank you~

**Comment by ivashmak** [comment]
Hi, the output model you get is actually projection matrix P = K [R | t], while in the ground truth file you see concatenated rotation and translation (ie, [R | t]). If you combine the ground truth intrinsic K and the GT R, t, you will get:

[[-190.897  1096.060 -230.741  293364.468]
 [ 513.670 -22.232 -985.457  159593.995]
 [-0.735  0.064 -0.675  834.593]]

This is closer to the estimated model.

**Comment by wanyunfeiAlex** [comment]
> Hi, the output model you get is actually projection matrix P = K [R | t], while in the ground truth file you see concatenated rotation and translation (ie, [R | t]). If you combine the ground truth intrinsic K and the GT R, t, you will get:
> 
> [[-190.897 1096.060 -230.741 293364.468] [ 513.670 -22.232 -985.457 159593.995] [-0.735 0.064 -0.675 834.593]]
> 
> This is closer to the estimated model.

Thanks a lot! It really helps~
