### ISSUE TITLE
error of python in version2

### ISSUE THREAD

**Issue by KHuang724** [ivashmak/vsac#7]
Nice job!
    However, when I compile c++ version and pybind respectively, the c++ version can run well but pybind version throw a error:
        import pvsac, numpy as np, cv2
        ImportError: /mypath/vsac/python/pvsac.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN8pose_lib14refine_relposeERKN2cv3MatERKSt6vectorIiSaIiEEiPNS_10CameraPoseERKNS_13BundleOptionsEPKd
    This problem does not exists in the master branch, which means both c++ version and pybind version can run well.
    Should I modify some function in python/bindings.cpp?

**Comment by ivashmak** [comment]
Hi @KHuang724, thank you. Sorry, for the late reply, I have found a bug in CMakeLists.txt and updated the verison2 branch. Please, try to compile and run again, and let me know if the problem still exists.
