### ISSUE TITLE
Image pairs of each dataset are missing

### ISSUE THREAD

**Issue by weitong8591** [ivashmak/vsac#9]
Hi! Thanks for the great work. Could you please provide the data you use for testing? i.e., four datasets (randomly selcted scenes) for H and F estimation. 

Best, 
Tong

**Comment by ivashmak** [comment]
Hi, thanks! I used PhotoTourism (sacre_coeur and st_paters_cathedral parts) and Kusvod datasets for Fundamental matrix. EVD (already divided I think for test/train) and HPatches datasets for Homography. Unfortunately, I do not remember specific instances I chose for testing, as it was all randomly selected.
